var crossConfig = {
  crossExcavation: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'steadyTubeMeasures',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    addFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'steadyTubeMeasures',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'steadyTubeMeasures',
    ],
  },
  crossPipeJacking: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    addFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
  },
  crossBoxCulvert: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    addFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
  },
  crossDrilling: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'enterAngle',
      'exitAngle',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
      'enterAngle',
      'exitAngle',
    ],
    addFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
      'enterAngle',
      'exitAngle',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
  },
  crossShield: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    addFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
    ],
  },
  crossDrillingBlasting: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'steadyTubeMeasures',
      'cofferdamGrade',
      'liningType',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    addFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'steadyTubeMeasures',
      'cofferdamGrade',
      'liningType',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'crossLength',
      'crossMaxLength',
      'steadyTubeMeasures',
      'cofferdamGrade',
      'liningType',
    ],
  },
  crossAcross: {
    searchFields: [ //
      'projectOid',
      'tendersOid',
      'pipelineOid',
      'crossOid',
      'startMedianStakeOid',
      'endMedianStakeOid',
    ],
    tableFields: [ //
      'approveStatus',
      'projectName',
      'tendersName',
      'pipelineName',
      'crossName',
      'crossingDepartment',
      'acrossTypeName',
      'crossLength',
      'crossMaxLength',
      'startMedianStakeCode',
      'startRelativeMileage',
      'endMedianStakeCode',
      'endRelativeMileage',
      'startPointx',
      'startPointy',
      'startPointz',
      'endPointx',
      'endPointy',
      'endPointz',
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',

    ],
    addFields1: [ //
      "projectOid",
      "tendersOid",
      "pipelineOid",
      "crossOid",
      'commencementDate',
      'completionDate',
      'constructUnit',
      'supervisionUnit',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
    ],
    addFields2: [ //
      'startMedianStakeOid',
      'endMedianStakeOid',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    addFields3: [ //
      'crossingDepartment',
      'acrossType',
      'crossLength',
      'crossMaxLength',
    ],
    detailFields1: [ //
      "projectName",
      "tendersName",
      "pipelineName",
      "crossName",
      'commencementDate',
      'completionDate',
      'constructUnitName',
      'supervisionUnitName',
      'supervisionEngineer',
      'collectionPerson',
      'collectionDate',
      'approveStatus'
    ],
    detailFields2: [ //
      'startMedianStakeCode',
      'endMedianStakeCode',
      'startRelativeMileage',
      'endRelativeMileage',
      'startPointx',
      'endPointx',
      'startPointy',
      'endPointy',
      'startPointz',
      'endPointz',
    ],
    detailFields3: [ //
      'crossingDepartment',
      'acrossTypeName',
      'crossLength',
      'crossMaxLength',
    ],
  },
  fieldsConfig: {
    projectOid: {
      type: 'select',
      name: '项目名称',
      optionUrl: '/daq/privilege/getProjectList.do',
      childSelect: ['tendersOid'],
      childUrl: ['/daq/privilege/getTendersList.do'],
      isRequired: true
    },
    projectName: {
      name: '项目名称',
    },
    tendersName: {
      name: '标段名称',
    },
    pipelineName: {
      name: '管线名称',
    },
    crossName: {
      name: '穿跨越名称',
    },
    tendersOid: {
      type: 'select',
      name: '标段名称',
      childSelect: ['pipelineOid', 'supervisionUnit'],
      childUrl: ['/daq/privilege/getPipelineListByTendersOid.do', '/daq/privilege/getSupervisionUnitByTendersOid.do'],
      isRequired: true
    },
    pipelineOid: {
      type: 'select',
      name: '管线名称',
      childSelect: ['crossOid'],
      childUrl: ['/daq/privilege/getCrossList.do'],
      isRequired: true
    },
    crossOid: {
      type: 'select',
      name: '穿跨越名称',
      childSelect: ['startMedianStakeOid', 'endMedianStakeOid'],
      childUrl: ['/daq/privilege/getMedianStakeList.do', '/daq/privilege/getMedianStakeList.do'],
      requestParams: {
        crossWay: 'cross_way_code01'
      },
      isRequired: true
    },
    startMedianStakeOid: {
      type: 'select',
      name: '起始桩号',
      isRequired: true
    },
    startMedianStakeCode: {
      name: '起始桩号',
    },
    startRelativeMileage: {
      type: 'number',
      name: '相对起始桩位置(m)',
      isRequired: true
    },
    endMedianStakeOid: {
      type: 'select',
      name: '结束桩号',
      isRequired: true
    },
    endMedianStakeCode: {
      name: '结束桩号',
    },
    endRelativeMileage: {
      type: 'number',
      name: '相对结束桩位置(m)',
      isRequired: true
    },
    commencementDate: {
      type: 'date',
      name: '开工日期',
    },
    completionDate: {
      type: 'date',
      name: '完工日期',
    },
    constructUnit: {
      type: 'select',
      name: '施工单位',
      isRequired: true
    },
    constructUnitName: {
      type: 'input',
      name: '施工单位',
    },
    supervisionUnit: {
      type: 'select',
      name: '监理单位',
    },
    supervisionUnitName: {
      type: 'input',
      name: '监理单位',
    },
    supervisionEngineer: {
      type: 'input',
      name: '监理工程师',
    },
    collectionPerson: {
      type: 'input',
      name: '采集人员',
    },
    collectionDate: {
      type: 'date',
      name: '采集日期',
    },
    startPointx: {
      type: 'number',
      name: '起始点X坐标',
      nameConfig: {
        crossDrilling: '入土点X坐标'
      }
    },
    startPointy: {
      type: 'number',
      name: '起始点Y坐标',
      nameConfig: {
        crossDrilling: '入土点Y坐标'
      }
    },
    startPointz: {
      type: 'number',
      name: '起始点高程(m)',
      nameConfig: {
        crossDrilling: '入土点高程(m)'
      }
    },
    endPointx: {
      type: 'number',
      name: '结束点X坐标',
      nameConfig: {
        crossDrilling: '出土点X坐标'
      }
    },
    endPointy: {
      type: 'number',
      name: '结束点Y坐标',
      nameConfig: {
        crossDrilling: '出土点Y坐标'
      }
    },
    endPointz: {
      type: 'number',
      name: '结束点高程(m)',
      nameConfig: {
        crossDrilling: '出土点高程(m)'
      }
    },
    enterAngle: {
      type: 'number',
      name: '入土角',
      max: 999999,
      precision: 6
    },
    exitAngle: {
      type: 'number',
      name: '出土角',
      max: 999999,
      precision: 6
    },
    crossingDepartment: {
      type: 'input',
      name: '穿越物管理单位',
    },
    crossLength: {
      type: 'number',
      name: '穿越长度(m)',
      max: 9999999,
      precision: 2
    },
    crossMaxLength: {
      type: 'number',
      name: '穿越最大深度(m)',
      max: 99999999,
      precision: 2
    },
    steadyTubeMeasures: {
      type: 'input',
      name: '稳管措施',
    },
    approveStatus: {
      type: 'input',
      name: '审核状态',
      formatter: function (a, b, value, c) {
        if (value == -1) return '驳回';
        // if (value == 0) return '未上报';
        if (value == 1) return '审核中';
        if (value == 2) return '通过';
        return '未上报';
      }
    },
    steadyTubeMeasures: {
      name: '稳管措施',
      type: 'input',
    },
    cofferdamGrade: {
      name: '钻爆围堰等级',
      type: 'input',
    },
    liningType: {
      name: '衬砌形式',
      type: 'input',
    },
    acrossTypeName: {
      name: '跨越类型'
    },
    acrossType: {
      type: 'select',
      name: '跨越类型',
      domainName: 'across_type_domain'
    },
  },
  methods: {
    formatFields: function (fields, fieldsConfig, templateCode) {
      return fields.map(function (item) {
        var nameConfig = fieldsConfig[item].nameConfig;
        return {
          name: (nameConfig && nameConfig[templateCode]) ? nameConfig[templateCode] : fieldsConfig[item].name,
          field: item,
          formatter: fieldsConfig[item].formatter,
        };
      });
    },
    formatForm: function (fields) {
      var obj = {};
      fields.forEach(function (item) {
        obj[item] = '';
      });
      obj.remarks = '';
      return obj;
    },
  },
  url: [
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006001&pageCode=crossExcavation&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.excavation.dao.entity.DaqCrossExcavation&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.excavation.query.DaqCrossExcavationQuery&templateCode=',
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006002&pageCode=crossPipeJacking&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.pipejacking.dao.entity.DaqCrossPipeJacking&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.pipejacking.query.DaqCrossPipeJackingQuery&templateCode=',
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006003&pageCode=crossBoxCulvert&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.boxculvert.dao.entity.DaqCrossBoxCulvert&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.boxculvert.query.DaqCrossBoxCulvertQuery&templateCode=',
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006004&pageCode=crossDrilling&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.drilling.dao.entity.DaqCrossDrilling&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.drilling.query.DaqCrossDrillingQuery&templateCode=',
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006005&pageCode=crossShield&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.shield.dao.entity.DaqCrossShield&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.shield.query.DaqCrossShieldQuery&templateCode=',
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006006&pageCode=crossDrillingBlasting&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.drillingblasting.dao.entity.DaqCrossDrillingBlasting&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.drillingblasting.query.DaqCrossDrillingBlastingQuery&templateCode=',
    '/jasmvvm/pages/row-cross/cross-template/cross-template.html?privilegeCode=P-daq-hq-001006007&pageCode=crossAcross&isApprove=1&className=cn.jasgroup.jasframework.acquisitiondata.material.cross.across.dao.entity.DaqCrossAcross&classNameQuery=cn.jasgroup.jasframework.acquisitiondata.material.cross.across.query.DaqCrossAcrossQuery&templateCode=',
  ]
};